version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - ./docker/db/.env
  db:
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    env_file:
      - ./docker/db/.env
    volumes:
      #- db-data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/db/data:/var/lib/mysql:rw
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile

volumes:
  app-web: {}
  db-data: {}
