easy_admin:
    entities:
        VariableGroup:
            class: PuzzleDetective\PuzzleBundle\Entity\VariableGroup
            translation_domain: 'PuzzleDetectivePuzzleBundle'
            form:
                fields:
                    - "name"
                    - "puzzle"
                    - "position"
            list:
                fields: ["id", "name"]
                sort: ["position", "ASC"]
            search:
                fields: ["id", "name"]
                sort: ["position", "ASC"]
