fos_rest:
#    disable_csrf_role: ROLE_API
    # the listener can also already set all configured query parameters as request attributes (force)
    param_fetcher_listener: 'force'
    body_listener: true
    format_listener:
        enabled: true
        rules:
            # setting fallback_format to json means that instead of considering the next rule in case of a priority mismatch,
            # json will be used
            - {
                path: '^/api',
                priorities: ['json', 'xml'],
                fallback_format: json,
                prefer_extension: true
              }
            - { path: '^/', stop: true }
    routing_loader:
        include_format: false
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=2.0']
        view_response_listener: 'force'
        formats:
            html: false
            json: true
            xml:  true
        templating_formats:
            html: false
            json: false
            xml:  false
    versioning:
        enabled: true
        resolvers:
            # Query parameter: /users?version=v1
            query: true
            # X-Accept-Version header
            custom_header: true
            # Accept header
            media_type:
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
        guessing_order:
            - query
            - custom_header
            - media_type
        default_version: 1.0
#    exception:
#        codes:
#            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
#            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
#        messages:
#            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
#    allowed_methods_listener: true
#    access_denied_listener:
#        json: true
