easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

puzzle_detective_app:
    resource: "@PuzzleDetectiveAppBundle/Resources/config/routing.xml"
    prefix:   /

puzzle_detective_puzzle:
    resource: "@PuzzleDetectivePuzzleBundle/Resources/config/routing.xml"
    prefix:   /

