easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

puzzle_detective_app:
    resource: "@PuzzleDetectiveAppBundle/Resources/config/routing.xml"
    prefix:   /

puzzle_detective_puzzle:
    resource: "@PuzzleDetectivePuzzleBundle/Resources/config/routing.xml"
    prefix:   /
