easy_admin:
    entities:
        User:
            class: PuzzleDetective\AppBundle\Entity\User
            controller: PuzzleDetective\AppBundle\Controller\UserAdminController
            # not a good idea, i.e. all menu items from all bundles must be translated in specified domain
#            translation_domain: 'PuzzleDetectiveAppBundle'
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            edit:
                fields:
                    - { property: 'plainPassword', type_options: { required: false} }
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true} }
                form_options: { validation_groups: ['Registration'] }
            list:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
