imports:
    - { resource: "@PuzzleDetectivePuzzleBundle/Resources/config/easyadmin/puzzle.yml" }
    - { resource: "@PuzzleDetectivePuzzleBundle/Resources/config/easyadmin/variable_group.yml" }
    - { resource: "@PuzzleDetectivePuzzleBundle/Resources/config/easyadmin/variable.yml" }

easy_admin:
    site_name: Puzzle Detective
    formats:
        date: Y-m-d
        time: H:i:s
        datetime: Y-m-d H:i:s
    list:
        actions:
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
        max_results: 25
