easy_admin:
    design:
        brand_color:  '#994db6'
#        color_scheme: 'light'
        menu:
            - { label: 'Puzzles' }
            - 'Puzzle'
            - 'VariableGroup'
            - 'Variable'
